import Footer from "./components/layout/footer";
import Headre from "./components/layout/Headre";
import NavBarFullSC from "./components/layout/NavBarFullSC";
import localFont from "next/font/local"
import "./globals.css";
import theme from "./them";
import { ThemeProvider } from "@mui/material";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <ThemeProvider theme={theme}>
        <Headre />
        {children}
        <Footer />
      </ThemeProvider>
    </body>
    </html >
  );
}
